language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"

install:
    - pip install -q coveralls --use-mirrors
    - pip install -r requirements.txt
    - pip install flake8

before_script:
    - flake8 strconv.py

script:
    - coverage run test_strconv.py

after_success:
    - coveralls
